version: '3'
services:
  dev:
    image: node:12-alpine
    volumes:
      - nodemodules:/opt/kubesphere/console/node_modules
      - .:/opt/kubesphere/console
    working_dir: /opt/kubesphere/console
    command: yarn start
    ports:
      - 8000:8000

volumes:
  nodemodules:
    external: true
